version: v0.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2022
platform: x64
configuration: Release
install:
- cmd: >-
    cd c:\tools\vcpkg

    set triplet=x64-windows-release
    vcpkg install                 ^
      miniz:%triplet%             ^
      nlohmann-json:%triplet%     ^
      stb:%triplet%               ^
      libsquish:%triplet%         ^
      glew:%triplet%              ^
      assimp:%triplet%            ^
      fmt:%triplet%

    vcpkg integrate install
cache: c:\tools\vcpkg\installed\
before_build:
- cmd: set CL=/DAPPVEYOR /DAPP_VERSION#\"%APPVEYOR_BUILD_VERSION%\"
build:
  project: c47edit.vcxproj
  verbosity: minimal
after_build:
- cmd: >-
    cd C:\projects\c47edit\%CONFIGURATION%

    7z a c47edit.zip c47edit.exe *.dll ..\classes.json
artifacts:
- path: '%CONFIGURATION%\c47edit.zip'
  name: c47edit.zip