version: v0.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2022
platform: x64
configuration: Release
install:
- cmd: >-
    cd c:\tools\vcpkg

    set triplet=x64-windows

    set APP_OUTPUT_RELATIVE_PATH=%PLATFORM%\%CONFIGURATION%

    vcpkg install
    miniz:%triplet%
    nlohmann-json:%triplet%
    stb:%triplet%
    libsquish:%triplet%
    glew:%triplet%
    assimp:%triplet%
    fmt:%triplet%

    vcpkg integrate install
before_build:
- cmd: set CL=/DAPPVEYOR /DAPP_VERSION#\"%APPVEYOR_BUILD_VERSION%\"
build:
  project: c47edit.vcxproj
  verbosity: minimal
after_build:
- cmd: >-
    cd C:\projects\c47edit\%APP_OUTPUT_RELATIVE_PATH%

    7z a c47edit.zip c47edit.exe *.dll C:\projects\c47edit\classes.json
artifacts:
- path: '%APP_OUTPUT_RELATIVE_PATH%\c47edit.zip'
  name: c47edit.zip